VL-archweb-master/devel/urls.py
from django.conf.urls.defaults import patterns

urlpatterns = patterns('devel.views',
    (r'^admin_log/$','admin_log'),
    (r'^admin_log/(?P<username>.*)/$','admin_log'),
    (r'^clock/$',    'clock', {},     'devel-clocks'),
    (r'^$',          'index', {},     'devel-index'),
    (r'^newuser/$',  'new_user_form'),
    (r'^profile/$',  'change_profile'),
    (r'^reports/(?P<report>.*)/(?P<username>.*)/$', 'report'),
    (r'^reports/(?P<report>.*)/$', 'report'),
)

# vim: set ts=4 sw=4 et:

VL-archweb-master/urls.py
import os.path

# Stupid Django. Don't remove these "unused" handler imports
from django.conf.urls.defaults import handler500, handler404, include, patterns
from django.conf import settings
from django.contrib import admin

from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page
from django.views.i18n import null_javascript_catalog

from feeds import PackageFeed, NewsFeed
import sitemaps

our_sitemaps = {
    'base':           sitemaps.BaseSitemap,
    'news':           sitemaps.NewsSitemap,
    'packages':       sitemaps.PackagesSitemap,
    'package-files':  sitemaps.PackageFilesSitemap,
    'package-groups': sitemaps.PackageGroupsSitemap,
    'split-packages': sitemaps.SplitPackagesSitemap,
}

admin.autodiscover()
urlpatterns = []

# Feeds patterns, used later
feeds_patterns = patterns('',
    (r'^$',          'public.views.feeds', {}, 'feeds-list'),
    (r'^news/$',     NewsFeed()),
    (r'^packages/$', PackageFeed()),
    (r'^packages/(?P<arch>[A-z0-9]+)/$',
        PackageFeed()),
    (r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
        PackageFeed()),
)

# Sitemaps
urlpatterns += patterns('django.contrib.sitemaps.views',
    # Thanks Django, we can't cache these longer because of
    # https://code.djangoproject.com/ticket/2713
    (r'^sitemap.xml$', 'index',
        {'sitemaps': our_sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
        {'sitemaps': our_sitemaps}),
)

# Authentication / Admin
urlpatterns += patterns('django.contrib.auth.views',
    (r'^login/$',           'login',  {
        'template_name': 'registration/login.html'}),
    (r'^logout/$',          'logout', {
        'template_name': 'registration/logout.html'}),
)

# Public pages
urlpatterns += patterns('public.views',
    (r'^$', 'index', {}, 'index'),
    (r'^about/$', TemplateView.as_view(template_name='public/about.html'),
        {}, 'page-about'),
    (r'^art/$',   TemplateView.as_view(template_name='public/art.html'),
        {}, 'page-art'),
    (r'^svn/$',   TemplateView.as_view(template_name='public/svn.html'),
        {}, 'page-svn'),
    (r'^developers/$',   'userlist', { 'user_type':'devs' },    'page-devs'),
    (r'^trustedusers/$', 'userlist', { 'user_type':'tus' },     'page-tus'),
    (r'^fellows/$',      'userlist', { 'user_type':'fellows' }, 'page-fellows'),
    (r'^donate/$',       'donate',   {}, 'page-donate'),
    (r'^download/$',     'download', {}, 'page-download'),
    (r'^master-keys/$',  'keys',     {}, 'page-keys'),
)

# Includes and other remaining stuff
urlpatterns += patterns('',
    # cache this static JS resource for 1 week rather than default 5 minutes
    (r'^jsi18n/$',   cache_page(604800)(null_javascript_catalog)),
    (r'^admin/',     include(admin.site.urls)),
    (r'^devel/',     include('devel.urls')),
    (r'^feeds/',     include(feeds_patterns)),
    (r'^groups/',    include('packages.urls_groups')),
    (r'^mirrorlist/',include('mirrors.urls_mirrorlist')),
    (r'^mirrors/',   include('mirrors.urls')),
    (r'^news/',      include('news.urls')),
    (r'^packages/',  include('packages.urls')),
    (r'^releng/',    include('releng.urls')),
    (r'^todo/',      include('todolists.urls')),
    (r'^visualize/', include('visualize.urls')),
    (r'^opensearch/packages/$', 'packages.views.opensearch',
        {}, 'opensearch-packages'),
    (r'^todolists/$','todolists.views.public_list'),
)

legacy_urls = (
    ('^about.php',     '/about/'),
    ('^changelog.php', '/packages/?sort=-last_update'),
    ('^download.php',  '/download/'),
    ('^index.php',     '/'),
    ('^logos.php',     '/art/'),
    ('^news.php',      '/news/'),
)

for old_url, new_url in legacy_urls:
    urlpatterns += patterns('django.views.generic.simple',
            (old_url, 'redirect_to', {'url': new_url}))

if settings.DEBUG == True:
    urlpatterns += patterns('',
        (r'^media/(.*)$', 'django.views.static.serve',
            {'document_root': os.path.join(settings.DEPLOY_PATH, 'media')}))

# vim: set ts=4 sw=4 et:

VL-archweb-master/devel/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

from main.fields import PGPKeyField


class MasterKey(models.Model):
    owner = models.ForeignKey(User, related_name='masterkey_owner',
        help_text="The developer holding this master key")
    revoker = models.ForeignKey(User, related_name='masterkey_revoker',
        help_text="The developer holding the revocation certificate")
    pgp_key = PGPKeyField(max_length=40, verbose_name="PGP key fingerprint",
        help_text="consists of 40 hex digits; use `gpg --fingerprint`")
    created = models.DateField()
    revoked = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('created',)

    def __unicode__(self):
        return u'%s, created %s' % (
                self.owner.get_full_name(), self.created)


class PGPSignature(models.Model):
    signer = PGPKeyField(max_length=40, verbose_name="PGP key fingerprint",
        help_text="consists of 40 hex digits; use `gpg --fingerprint`")
    signee = PGPKeyField(max_length=40, verbose_name="PGP key fingerprint",
        help_text="consists of 40 hex digits; use `gpg --fingerprint`")
    created = models.DateField()
    expires = models.DateField(null=True, blank=True)
    valid = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'PGP signature'

    def __unicode__(self):
        return u'%s → %s' % (self.signer, self.signee)

# vim: set ts=4 sw=4 et:

VL-archweb-master/main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sites.models import Site

from .fields import PositiveBigIntegerField, PGPKeyField
from .utils import cache_function, make_choice, set_created_field

from datetime import datetime
from itertools import groupby
import pytz


class UserProfile(models.Model):
    notify = models.BooleanField(
        "Send notifications",
        default=True,
        help_text="When enabled, send user 'flag out-of-date' notifications")
    time_zone = models.CharField(
        max_length=100,
        choices=make_choice(pytz.common_timezones),
        default="UTC",
        help_text="Used for developer clock page")
    alias = models.CharField(
        max_length=50,
        help_text="Required field")
    public_email = models.CharField(
        max_length=50,
        help_text="Required field")
    other_contact = models.CharField(max_length=100, null=True, blank=True)
    pgp_key = PGPKeyField(max_length=40, null=True, blank=True,
        verbose_name="PGP key fingerprint",
        help_text="consists of 40 hex digits; use `gpg --fingerprint`")
    website = models.CharField(max_length=200, null=True, blank=True)
    yob = models.IntegerField("Year of birth", null=True, blank=True)
    location = models.CharField(max_length=50, null=True, blank=True)
    languages = models.CharField(max_length=50, null=True, blank=True)
    interests = models.CharField(max_length=255, null=True, blank=True)
    occupation = models.CharField(max_length=50, null=True, blank=True)
    roles = models.CharField(max_length=255, null=True, blank=True)
    favorite_distros = models.CharField(max_length=255, null=True, blank=True)
    picture = models.FileField(upload_to='devs', default='devs/silhouette.png',
        help_text="Ideally 125px by 125px")
    user = models.OneToOneField(User, related_name='userprofile')
    allowed_repos = models.ManyToManyField('Repo', blank=True)
    latin_name = models.CharField(max_length=255, null=True, blank=True,
        help_text="Latin-form name; used only for non-Latin full names")

    class Meta:
        db_table = 'user_profiles'
        verbose_name = 'Additional Profile Data'
        verbose_name_plural = 'Additional Profile Data'

    def get_absolute_url(self):
        # TODO: this is disgusting. find a way to consolidate this logic with
        # public.views.userlist among other places, and make some constants or
        # something so we aren't using copies of string names everywhere.
        group_names = self.user.groups.values_list('name', flat=True)
        if "Developers" in group_names:
            prefix = "developers"
        elif "Trusted Users" in group_names:
            prefix = "trustedusers"
        else:
            prefix = "fellows"
        return '/%s/#%s' % (prefix, self.user.username)

class TodolistManager(models.Manager):
    def incomplete(self):
        return self.filter(todolistpkg__complete=False).distinct()

class PackageManager(models.Manager):
    def flagged(self):
        """Used by dev dashboard."""
        return self.filter(flag_date__isnull=False)

    def signed(self):
        """Used by dev dashboard."""
        return self.filter(pgp_signature__isnull=False)

    def normal(self):
        return self.select_related('arch', 'repo')

class Donor(models.Model):
    name = models.CharField(max_length=255, unique=True)
    visible = models.BooleanField(default=True,
            help_text="Should we show this donor on the public page?")
    created = models.DateTimeField()

    def __unicode__(self):
        return self.name

    class Meta:
        db_table = 'donors'
        ordering = ('name',)
        get_latest_by = 'when'

class Arch(models.Model):
    name = models.CharField(max_length=255, unique=True)
    agnostic = models.BooleanField(default=False,
            help_text="Is this architecture non-platform specific?")

    def __unicode__(self):
        return self.name

    def __lt__(self, other):
        return self.name < other.name

    class Meta:
        db_table = 'arches'
        ordering = ['name']
        verbose_name_plural = 'arches'

class Repo(models.Model):
    name = models.CharField(max_length=255, unique=True)
    testing = models.BooleanField(default=False,
            help_text="Is this repo meant for package testing?")
    staging = models.BooleanField(default=False,
            help_text="Is this repo meant for package staging?")
    bugs_project = models.SmallIntegerField(default=1,
            help_text="Flyspray project ID for this repository.")
    bugs_category = models.SmallIntegerField(default=0,
            help_text="Flyspray category ID for this repository.")
    svn_root = models.CharField(max_length=64,
            help_text="SVN root (e.g. path) for this repository.")

    def __unicode__(self):
        return self.name

    def __lt__(self, other):
        return self.name < other.name

    class Meta:
        db_table = 'repos'
        ordering = ['name']
        verbose_name_plural = 'repos'

class Package(models.Model):
    repo = models.ForeignKey(Repo, related_name="packages",
            on_delete=models.PROTECT)
    arch = models.ForeignKey(Arch, related_name="packages",
            on_delete=models.PROTECT)
    pkgname = models.CharField(max_length=255)
    pkgbase = models.CharField(max_length=255, db_index=True)
    pkgver = models.CharField(max_length=255)
    pkgrel = models.CharField(max_length=255)
    epoch = models.PositiveIntegerField(default=0)
    pkgdesc = models.TextField(null=True)
    url = models.CharField(max_length=255, null=True)
    filename = models.CharField(max_length=255)
    compressed_size = PositiveBigIntegerField()
    installed_size = PositiveBigIntegerField()
    build_date = models.DateTimeField(null=True)
    last_update = models.DateTimeField()
    files_last_update = models.DateTimeField(null=True, blank=True)
    packager_str = models.CharField(max_length=255)
    packager = models.ForeignKey(User, null=True,
            on_delete=models.SET_NULL)
    pgp_signature = models.TextField(null=True, blank=True)
    flag_date = models.DateTimeField(null=True)

    objects = PackageManager()

    class Meta:
        db_table = 'packages'
        ordering = ('pkgname',)
        get_latest_by = 'last_update'
        unique_together = (('pkgname', 'repo', 'arch'),)

    def __unicode__(self):
        return self.pkgname

    @property
    def full_version(self):
        if self.epoch > 0:
            return u'%d:%s-%s' % (self.epoch, self.pkgver, self.pkgrel)
        return u'%s-%s' % (self.pkgver, self.pkgrel)

    def get_absolute_url(self):
        return '/packages/%s/%s/%s/' % (self.repo.name.lower(),
                self.arch.name, self.pkgname)

    def get_full_url(self, proto='https'):
        '''get a URL suitable for things like email including the domain'''
        domain = Site.objects.get_current().domain
        return '%s://%s%s' % (proto, domain, self.get_absolute_url())

    def is_signed(self):
        return bool(self.pgp_signature)

    _maintainers = None

    @property
    def maintainers(self):
        from packages.models import PackageRelation
        if self._maintainers is None:
            self._maintainers = User.objects.filter(
                    package_relations__pkgbase=self.pkgbase,
                    package_relations__type=PackageRelation.MAINTAINER)
        return self._maintainers

    @maintainers.setter
    def maintainers(self, maintainers):
        self._maintainers = maintainers

    @cache_function(300)
    def applicable_arches(self):
        '''The list of (this arch) + (available agnostic arches).'''
        arches = set(Arch.objects.filter(agnostic=True))
        arches.add(self.arch)
        return list(arches)

    @cache_function(300)
    def get_requiredby(self):
        """
        Returns a list of package objects. An attempt will be made to keep this
        list slim by including the corresponding package in the same testing
        category as this package if that check makes sense.
        """
        provides = set(self.provides.values_list('name', flat=True))
        provides.add(self.pkgname)
        requiredby = PackageDepend.objects.select_related('pkg',
                'pkg__arch', 'pkg__repo').filter(
                depname__in=provides).order_by(
                'pkg__pkgname', 'pkg__arch__name', 'pkg__repo__name')
        if not self.arch.agnostic:
            # make sure we match architectures if possible
            requiredby = requiredby.filter(
                    pkg__arch__in=self.applicable_arches())
        # sort out duplicate packages; this happens if something has a double
        # versioned dep such as a kernel module
        requiredby = [list(vals)[0] for _, vals in
                groupby(requiredby, lambda x: x.pkg.id)]

        # find another package by this name in the opposite testing setup
        # TODO: figure out staging exclusions too
        if not Package.objects.filter(pkgname=self.pkgname,
                arch=self.arch).exclude(id=self.id).exclude(
                repo__testing=self.repo.testing).exists():
            # there isn't one? short circuit, all required by entries are fine
            return requiredby

        trimmed = []
        # for each unique package name, try to screen our package list down to
        # those packages in the same testing category (yes or no) iff there is
        # a package in the same testing category.
        for _, dep_pkgs in groupby(requiredby, lambda x: x.pkg.pkgname):
            dep_pkgs = list(dep_pkgs)
            dep = dep_pkgs[0]
            if len(dep_pkgs) > 1:
                dep_pkgs = [d for d in dep_pkgs
                        if d.pkg.repo.testing == self.repo.testing and
                        d.pkg.repo.staging == self.repo.staging]
                if len(dep_pkgs) > 0:
                    dep = dep_pkgs[0]
            trimmed.append(dep)

VL-archweb-master/templates/devel/index.html
{% extends "base.html" %}
{% load cache %}
{% load package_extras %}

{% block title %}Arch Linux - Developer Dashboard{% endblock %}

{% block content %}
<div id="dev-dashboard" class="box">

    <h2>Developer Dashboard</h2>

    <h3>My Flagged Packages</h3>

    <table id="dash-myflagged" class="results">
        <thead>
            <tr>
                <th>Name</th>
                <th>Version</th>
                <th>Repo</th>
                <th>Arch</th>
                <th>Flagged</th>
                <th>Last Updated</th>
            </tr>
        </thead>
        <tbody>
            {% for pkg in flagged %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td>{% pkg_details_link pkg %}</td>
                    <td>{{ pkg.full_version }}</td>
                    <td>{{ pkg.repo.name }}</td>
                    <td>{{ pkg.arch.name }}</td>
                    <td>{{ pkg.flag_date|date }}</td>
                    <td>{{ pkg.last_update|date }}</td>
                </tr>
            {% empty %}
                <tr class="empty"><td colspan="6"><em>No flagged packages to display</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>My Incomplete Todo List Packages</h3>

    <table id="dash-mytodolist" class="results">
        <thead>
            <tr>
                <th>Todo List</th>
                <th>Name</th>
                <th>Repo</th>
                <th>Arch</th>
                <th>Maintainer(s)</th>
            </tr>
        </thead>
        <tbody>
            {% for todopkg in todopkgs %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td><a href="{{ todopkg.list.get_absolute_url }}"
                            title="View todo list: {{ todopkg.list.name }}">{{ todopkg.list.name }}</a></td>
                    <td>{% pkg_details_link todopkg.pkg %}</td>
                    <td>{{ todopkg.pkg.repo.name }}</td>
                    <td>{{ todopkg.pkg.arch.name }}</td>
                    <td>{{ todopkg.pkg.maintainers|join:', ' }}</td>
                </tr>
            {% empty %}
                <tr class="empty"><td colspan="5"><em>No incomplete todo list packages to display</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Package Todo Lists</h3>

    <table id="dash-todo" class="results">
        <thead>
            <tr>
                <th>Name</th>
                <th>Creation Date</th>
                <th>Creator</th>
                <th>Description</th>
                <th>Package Count</th>
                <th>Incomplete Count</th>
            </tr>
        </thead>
        <tbody>
            {% for todo in todos %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td><a href="{{ todo.get_absolute_url }}"
                        title="View todo list: {{ todo.name }}">{{ todo.name }}</a></td>
                <td>{{ todo.date_added|date }}</td>
                <td>{{ todo.creator.get_full_name }}</td>
                <td class="wrap">{{ todo.description|urlize }}</td>
                <td>{{ todo.pkg_count }}</td>
                <td>{{ todo.incomplete_count }}</td>
            </tr>
            {% empty %}
            <tr class="empty"><td colspan="6"><em>No package todo lists to display</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Signoff Status</h3>

    <table id="dash-signoffs" class="results">
        <thead>
            <tr>
                <th>Name</th>
                <th>Version</th>
                <th>Arch</th>
                <th>Target Repo</th>
                <th>Last Updated</th>
                <th>Approved</th>
                <th>Signoffs</th>
            </tr>
        </thead>
        <tbody>
            {% for group in signoffs %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td>{% pkg_details_link group.package %}</td>
                <td>{{ group.version }}</td>
                <td>{{ group.arch.name }}</td>
                <td>{{ group.target_repo }}</td>
                <td>{{ group.last_update|date }}</td>
                {% if group.specification.known_bad %}
                <td class="approval signoff-bad">Bad</td>
                {% else %}
                {% if not group.specification.enabled %}
                <td class="approval signoff-disabled">Disabled</td>
                {% else %}
                <td class="approval signoff-{{ group.approved|yesno }}">{{ group.approved|yesno|capfirst }}</td>
                {% endif %}
                {% endif %}
                <td><ul class="signoff-list">
                    {% for signoff in group.signoffs %}
                    <li class="signed-username" title="Signed off by {{ signoff.user }}">{{ signoff.user }}{% if signoff.revoked %} (revoked){% endif %}</li>
                    {% endfor %}
                </ul></td>
            </tr>
            {% empty %}
            <tr class="empty"><td colspan="7"><em>No packages you maintain or have packaged need signoffs</em></td></tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Developer Reports</h3>
    <ul>
        <li><a href="reports/big/">Big</a>:
        All packages with compressed size &gt; 50 MiB
        (<a href="reports/big/{{ user.username }}/">yours only</a>)</li>
        <li><a href="reports/old/">Old</a>:
        Packages last built more than two years ago
        (<a href="reports/old/{{ user.username }}/">yours only</a>)</li>
        <li><a href="reports/long-out-of-date/">Long Out-of-date</a>:
        Packages marked out-of-date more than 90 days ago
        (<a href="reports/long-out-of-date/{{ user.username }}/">yours only</a>)</li>
        <li><a href="reports/uncompressed-man/">Uncompressed Manpages</a>:
        Self-explanatory
        (<a href="reports/uncompressed-man/{{ user.username }}/">yours only</a>)</li>
        <li><a href="reports/uncompressed-info/">Uncompressed Info Pages</a>:
        Self-explanatory
        (<a href="reports/uncompressed-info/{{ user.username }}/">yours only</a>)</li>
        <li><a href="reports/badcompression/">Bad Compression</a>:
        Packages with a compression ratio of less than 10%
        (<a href="reports/badcompression/{{ user.username }}/">yours only</a>)</li>
        <li><a href="reports/unneeded-orphans/">Unneeded Orphans</a>:
        Packages that have no maintainer and are not required by any other
        package in any repository</li>
    </ul>

</div><!-- #dev-dashboard -->

{% cache 60 dev-dash-by-arch %}
<div id="dash-by-arch" class="box">

    <h2>Stats by Architecture</h2>

    <table id="stats-by-arch" class="results dash-stats">
        <thead>
            <tr>
                <th class="key">Arch</th>
                <th># Packages</th>
                <th># Flagged</th>
                <th># Signed</th>
            </tr>
        </thead>
        <tbody>
            {% for arch in arches %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td>{{ arch.name }}</td>
                    <td><a href="/packages/?arch={{ arch.name }}"
                            title="View all packages for the {{ arch.name }} architecture">
                            <strong>{{ arch.packages.count }}</strong> packages</a></td>
                    <td><a href="/packages/?arch={{ arch.name }}&amp;flagged=Flagged"
                            title="View all flagged packages for the {{ arch.name }} architecture">
                            <strong>{{ arch.packages.flagged.count }}</strong> packages</a></td>

                    <td><strong>{{ arch.packages.signed.count }}</strong> packages</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>{# #dash-by-arch #}
{% endcache %}

{% cache 60 dev-dash-by-repo %}
<div id="dash-by-repo" class="box">

    <h2>Stats by Repository</h2>

    <table id="stats-by-repo" class="results dash-stats">
        <thead>
            <tr>
                <th class="key">Repository</th>
                <th># Packages</th>
                <th># Flagged</th>
                <th># Signed</th>
            </tr>
        </thead>
        <tbody>
            {% for repo in repos %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td>{{ repo.name }}</td>
                    <td><a href="/packages/?repo={{ repo.name }}"
                            title="View all packages in the {{ repo.name }} repository">
                            <strong>{{ repo.packages.count }}</strong> packages</a></td>
                    <td><a href="/packages/?repo={{ repo.name }}&amp;flagged=Flagged"
                            title="View all flagged packages in the {{ repo.name }} repository">
                            <strong>{{ repo.packages.flagged.count }}</strong> packages</a></td>
                    <td><strong>{{ repo.packages.signed.count }}</strong> packages</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>{# dash-by-arch #}
{% endcache %}

{% cache 60 dev-dash-by-developer %}
<div id="dash-by-developer" class="box">

    <h2>Stats by Developer</h2>

    {% if perms.main.change_package %}
    <p><a href="/packages/stale_relations/">Look for stale relations</a></p>
    {% endif %}

    <table id="stats-by-maintainer" class="results dash-stats">
        <thead>
            <tr>
                <th class="key">Maintainer</th>
                <th># Maintained</th>
                <th># Flagged</th>
                <th># Last Packager</th>
            </tr>
            <tr class="even">
                <td><em>Orphan/Unknown</em></td>
                <td><a href="/packages/?maintainer=orphan"
                        title="View all orphan packages">
                        <strong>{{ orphan.package_count }}</strong> packages</a>
                </td>
                <td><a href="/packages/?maintainer=orphan&amp;flagged=Flagged"
                        title="View all flagged orphan packages">
                        <strong>{{ orphan.flagged_count }}</strong> packages</a>
                </td>
                <td><a href="/packages/?packager=unknown"
                        title="View all packages last updated by unknown">
                        <strong>{{ orphan.updated_count }}</strong> packages</a>
                </td>
            </tr>
        </thead>
        <tbody>
            {% for maint in maintainers %}
                <tr class="{% cycle 'odd' 'even' %}">
                    <td>{{ maint.get_full_name }}</td>
                    <td><a href="/packages/?maintainer={{ maint.username }}"
                            title="View all packages maintained by {{ maint.get_full_name }}">
                            <strong>{{ maint.package_count }}</strong> packages</a>
                    </td>
                    <td><a href="/packages/?maintainer={{ maint.username }}&amp;flagged=Flagged"
                            title="View all flagged packages maintained by {{ maint.get_full_name }}">
                            <strong>{{ maint.flagged_count }}</strong> packages</a>
                    </td>
                    <td><a href="/packages/?packager={{ maint.username }}"
                            title="View all packages last updated by {{ maint.get_full_name }}">
                            <strong>{{ maint.updated_count }}</strong> packages</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>{# #dash-by-developer #}
{% endcache %}

{% load cdn %}{% jquery %}
<script type="text/javascript" src="{{ STATIC_URL }}jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}archweb.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#dash-myflagged:not(:has(tbody tr.empty))").tablesorter(
        {widgets: ['zebra'], sortList: [[0,0]]});
    $("#dash-mytodolist:not(:has(tbody tr.empty))").tablesorter(
        {widgets: ['zebra'], sortList: [[0,0], [1,0]]});
    $("#dash-todo:not(:has(tbody tr.empty))").tablesorter(
            {widgets: ['zebra'], sortList: [[1,1]]});
    $("#dash-signoffs:not(:has(tbody tr.empty))").tablesorter({
            widgets: ['zebra'],
            sortList: [[0,0]],
            headers: { 6: {sorter: false } }
    });
    $(".dash-stats").tablesorter({
        widgets: ['zebra'],
        sortList: [[0,0]],
        headers: { 1: { sorter: 'pkgcount' }, 2: { sorter: 'pkgcount' }, 3: { sorter: 'pkgcount' } }
    });
});
</script>
{% endblock %}