VL-archweb-master/mirrors/urls.py
from django.conf.urls.defaults import patterns

urlpatterns = patterns('mirrors.views',
    (r'^$',                     'mirrors', {}, 'mirror-list'),
    (r'^status/$',              'status',  {}, 'mirror-status'),
    (r'^status/json/$',         'status_json',  {}, 'mirror-status-json'),
    (r'^(?P<name>[\.\-\w]+)/$', 'mirror_details'),
)

# vim: set ts=4 sw=4 et:

VL-archweb-master/urls.py
import os.path

# Stupid Django. Don't remove these "unused" handler imports
from django.conf.urls.defaults import handler500, handler404, include, patterns
from django.conf import settings
from django.contrib import admin

from django.views.generic import TemplateView
from django.views.decorators.cache import cache_page
from django.views.i18n import null_javascript_catalog

from feeds import PackageFeed, NewsFeed
import sitemaps

our_sitemaps = {
    'base':           sitemaps.BaseSitemap,
    'news':           sitemaps.NewsSitemap,
    'packages':       sitemaps.PackagesSitemap,
    'package-files':  sitemaps.PackageFilesSitemap,
    'package-groups': sitemaps.PackageGroupsSitemap,
    'split-packages': sitemaps.SplitPackagesSitemap,
}

admin.autodiscover()
urlpatterns = []

# Feeds patterns, used later
feeds_patterns = patterns('',
    (r'^$',          'public.views.feeds', {}, 'feeds-list'),
    (r'^news/$',     NewsFeed()),
    (r'^packages/$', PackageFeed()),
    (r'^packages/(?P<arch>[A-z0-9]+)/$',
        PackageFeed()),
    (r'^packages/(?P<arch>[A-z0-9]+)/(?P<repo>[A-z0-9\-]+)/$',
        PackageFeed()),
)

# Sitemaps
urlpatterns += patterns('django.contrib.sitemaps.views',
    # Thanks Django, we can't cache these longer because of
    # https://code.djangoproject.com/ticket/2713
    (r'^sitemap.xml$', 'index',
        {'sitemaps': our_sitemaps}),
    (r'^sitemap-(?P<section>.+)\.xml$', 'sitemap',
        {'sitemaps': our_sitemaps}),
)

# Authentication / Admin
urlpatterns += patterns('django.contrib.auth.views',
    (r'^login/$',           'login',  {
        'template_name': 'registration/login.html'}),
    (r'^logout/$',          'logout', {
        'template_name': 'registration/logout.html'}),
)

# Public pages
urlpatterns += patterns('public.views',
    (r'^$', 'index', {}, 'index'),
    (r'^about/$', TemplateView.as_view(template_name='public/about.html'),
        {}, 'page-about'),
    (r'^art/$',   TemplateView.as_view(template_name='public/art.html'),
        {}, 'page-art'),
    (r'^svn/$',   TemplateView.as_view(template_name='public/svn.html'),
        {}, 'page-svn'),
    (r'^developers/$',   'userlist', { 'user_type':'devs' },    'page-devs'),
    (r'^trustedusers/$', 'userlist', { 'user_type':'tus' },     'page-tus'),
    (r'^fellows/$',      'userlist', { 'user_type':'fellows' }, 'page-fellows'),
    (r'^donate/$',       'donate',   {}, 'page-donate'),
    (r'^download/$',     'download', {}, 'page-download'),
    (r'^master-keys/$',  'keys',     {}, 'page-keys'),
)

# Includes and other remaining stuff
urlpatterns += patterns('',
    # cache this static JS resource for 1 week rather than default 5 minutes
    (r'^jsi18n/$',   cache_page(604800)(null_javascript_catalog)),
    (r'^admin/',     include(admin.site.urls)),
    (r'^devel/',     include('devel.urls')),
    (r'^feeds/',     include(feeds_patterns)),
    (r'^groups/',    include('packages.urls_groups')),
    (r'^mirrorlist/',include('mirrors.urls_mirrorlist')),
    (r'^mirrors/',   include('mirrors.urls')),
    (r'^news/',      include('news.urls')),
    (r'^packages/',  include('packages.urls')),
    (r'^releng/',    include('releng.urls')),
    (r'^todo/',      include('todolists.urls')),
    (r'^visualize/', include('visualize.urls')),
    (r'^opensearch/packages/$', 'packages.views.opensearch',
        {}, 'opensearch-packages'),
    (r'^todolists/$','todolists.views.public_list'),
)

legacy_urls = (
    ('^about.php',     '/about/'),
    ('^changelog.php', '/packages/?sort=-last_update'),
    ('^download.php',  '/download/'),
    ('^index.php',     '/'),
    ('^logos.php',     '/art/'),
    ('^news.php',      '/news/'),
)

for old_url, new_url in legacy_urls:
    urlpatterns += patterns('django.views.generic.simple',
            (old_url, 'redirect_to', {'url': new_url}))

if settings.DEBUG == True:
    urlpatterns += patterns('',
        (r'^media/(.*)$', 'django.views.static.serve',
            {'document_root': os.path.join(settings.DEPLOY_PATH, 'media')}))

# vim: set ts=4 sw=4 et:

VL-archweb-master/mirrors/models.py
import socket
from urlparse import urlparse

from django.db import models
from django.core.exceptions import ValidationError

class NullCharField(models.CharField):
    description = "String (up to %(max_length)s), NULL if value is empty"
    _south_introspects = True

    def get_prep_value(self, value):
        if value == '':
            return None
        return self.to_python(value)

TIER_CHOICES = (
    (0, 'Tier 0'),
    (1, 'Tier 1'),
    (2, 'Tier 2'),
    (-1, 'Untiered'),
)

class Mirror(models.Model):
    name = models.CharField(max_length=255, unique=True)
    tier = models.SmallIntegerField(default=2, choices=TIER_CHOICES)
    upstream = models.ForeignKey('self', null=True, on_delete=models.SET_NULL)
    country = models.CharField(max_length=255, db_index=True)
    admin_email = models.EmailField(max_length=255, blank=True)
    public = models.BooleanField(default=True)
    active = models.BooleanField(default=True)
    isos = models.BooleanField("ISOs", default=True)
    rsync_user = models.CharField(max_length=50, blank=True, default='')
    rsync_password = models.CharField(max_length=50, blank=True, default='')
    notes = models.TextField(blank=True)

    class Meta:
        ordering = ('country', 'name')

    def __unicode__(self):
        return self.name

    def supported_protocols(self):
        protocols = MirrorProtocol.objects.filter(
                urls__mirror=self).order_by('protocol').distinct()
        return sorted(protocols)

    def downstream(self):
        return Mirror.objects.filter(upstream=self).order_by('name')

    def get_absolute_url(self):
        return '/mirrors/%s/' % self.name

class MirrorProtocol(models.Model):
    protocol = models.CharField(max_length=10, unique=True)
    is_download = models.BooleanField(default=True,
            help_text="Is protocol useful for end-users, e.g. FTP/HTTP")

    def __unicode__(self):
        return self.protocol

    class Meta:
        ordering = ('protocol',)

class MirrorUrl(models.Model):
    url = models.CharField("URL", max_length=255, unique=True)
    protocol = models.ForeignKey(MirrorProtocol, related_name="urls",
            editable=False, on_delete=models.PROTECT)
    mirror = models.ForeignKey(Mirror, related_name="urls")
    country = NullCharField(max_length=255, null=True, blank=True,
            db_index=True)
    has_ipv4 = models.BooleanField("IPv4 capable", default=True,
            editable=False)
    has_ipv6 = models.BooleanField("IPv6 capable", default=False,
            editable=False)

    def address_families(self):
        hostname = urlparse(self.url).hostname
        info = socket.getaddrinfo(hostname, None, 0, socket.SOCK_STREAM)
        families = [x[0] for x in info]
        return families

    @property
    def hostname(self):
        return urlparse(self.url).hostname

    @property
    def real_country(self):
        return self.country or self.mirror.country

    def clean(self):
        try:
            # Auto-map the protocol field by looking at the URL
            protocol = urlparse(self.url).scheme
            self.protocol = MirrorProtocol.objects.get(protocol=protocol)
        except Exception as e:
            raise ValidationError(e)
        try:
            families = self.address_families()
            self.has_ipv4 = socket.AF_INET in families
            self.has_ipv6 = socket.AF_INET6 in families
        except socket.error as e:
            # We don't fail in this case; we'll just set both to False
            self.has_ipv4 = False
            self.has_ipv6 = False

    def __unicode__(self):
        return self.url

    class Meta:
        verbose_name = 'mirror URL'

class MirrorRsync(models.Model):
    ip = models.CharField("IP", max_length=24)
    mirror = models.ForeignKey(Mirror, related_name="rsync_ips")

    def __unicode__(self):
        return "%s" % (self.ip)

    class Meta:
        verbose_name = 'mirror rsync IP'

class MirrorLog(models.Model):
    url = models.ForeignKey(MirrorUrl, related_name="logs")
    check_time = models.DateTimeField(db_index=True)
    last_sync = models.DateTimeField(null=True)
    duration = models.FloatField(null=True)
    is_success = models.BooleanField(default=True)
    error = models.CharField(max_length=255, blank=True, default='')

    def __unicode__(self):
        return "Check of %s at %s" % (self.url.url, self.check_time)

    class Meta:
        verbose_name = 'mirror check log'

# vim: set ts=4 sw=4 et:

VL-archweb-master/mirrors/views.py
from django import forms
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.simple import direct_to_template
from django.utils import simplejson

from main.utils import make_choice
from .models import Mirror, MirrorUrl, MirrorProtocol
from .utils import get_mirror_statuses, get_mirror_errors

import datetime

class MirrorlistForm(forms.Form):
    country = forms.MultipleChoiceField(required=False)
    protocol = forms.MultipleChoiceField(required=False)
    ip_version = forms.MultipleChoiceField(required=False,
            label="IP version", choices=(('4','IPv4'), ('6','IPv6')))
    use_mirror_status = forms.BooleanField(required=False)

    def __init__(self, *args, **kwargs):
        super(MirrorlistForm, self).__init__(*args, **kwargs)
        countries = Mirror.objects.filter(active=True).values_list(
                'country', flat=True).distinct().order_by('country')
        self.fields['country'].choices = [('all','All')] + make_choice(
                countries)
        self.fields['country'].initial = ['all']
        protos = make_choice(
                MirrorProtocol.objects.filter(is_download=True))
        self.fields['protocol'].choices = protos
        self.fields['protocol'].initial = [t[0] for t in protos]
        self.fields['ip_version'].initial = ['4']

@csrf_exempt
def generate_mirrorlist(request):
    if request.method == 'POST' or len(request.GET) > 0:
        form = MirrorlistForm(data=request.REQUEST)
        if form.is_valid():
            countries = form.cleaned_data['country']
            protocols = form.cleaned_data['protocol']
            use_status = form.cleaned_data['use_mirror_status']
            ipv4 = '4' in form.cleaned_data['ip_version']
            ipv6 = '6' in form.cleaned_data['ip_version']
            return find_mirrors(request, countries, protocols,
                    use_status, ipv4, ipv6)
    else:
        form = MirrorlistForm()

    return direct_to_template(request, 'mirrors/index.html', {'mirrorlist_form': form})

def find_mirrors(request, countries=None, protocols=None, use_status=False,
        ipv4_supported=True, ipv6_supported=True):
    if not protocols:
        protocols = MirrorProtocol.objects.filter(
                is_download=True).values_list('protocol', flat=True)
    qset = MirrorUrl.objects.select_related().filter(
            protocol__protocol__in=protocols,
            mirror__public=True, mirror__active=True,
    )
    if countries and 'all' not in countries:
        qset = qset.filter(Q(country__in=countries) |
                Q(mirror__country__in=countries))

    ip_version = Q()
    if ipv4_supported:
        ip_version |= Q(has_ipv4=True)
    if ipv6_supported:
        ip_version |= Q(has_ipv6=True)
    qset = qset.filter(ip_version)

    if not use_status:
        urls = qset.order_by('mirror__name', 'url')
        urls = sorted(urls, key=lambda x: x.real_country)
        template = 'mirrors/mirrorlist.txt'
    else:
        status_info = get_mirror_statuses()
        scores = dict([(u.id, u.score) for u in status_info['urls']])
        urls = []
        for u in qset:
            u.score = scores.get(u.id, None)
            # also include mirrors that don't have an up to date score
            # (as opposed to those that have been set with no score)
            if (u.id not in scores) or \
                    (u.score and u.score < 100.0):
                urls.append(u)
        # if a url doesn't have a score, treat it as the highest possible
        urls = sorted(urls, key=lambda x: x.score or 100.0)
        template = 'mirrors/mirrorlist_status.txt'

    return direct_to_template(request, template, {
                'mirror_urls': urls,
            },
            mimetype='text/plain')

def mirrors(request):
    mirror_list = Mirror.objects.select_related().order_by('tier', 'country')
    if not request.user.is_authenticated():
        mirror_list = mirror_list.filter(public=True, active=True)
    return direct_to_template(request, 'mirrors/mirrors.html',
            {'mirror_list': mirror_list})

def mirror_details(request, name):
    mirror = get_object_or_404(Mirror, name=name)
    if not request.user.is_authenticated() and \
            (not mirror.public or not mirror.active):
        raise Http404

    status_info = get_mirror_statuses()
    checked_urls = [url for url in status_info['urls'] \
            if url.mirror_id == mirror.id]
    all_urls = mirror.urls.select_related('protocol')
    # get each item from checked_urls and supplement with anything in all_urls
    # if it wasn't there
    all_urls = set(checked_urls).union(all_urls)
    all_urls = sorted(all_urls, key=lambda x: x.url)

    return direct_to_template(request, 'mirrors/mirror_details.html',
            {'mirror': mirror, 'urls': all_urls})

def status(request):
    bad_timedelta = datetime.timedelta(days=3)
    status_info = get_mirror_statuses()

    urls = status_info['urls']
    good_urls = []
    bad_urls = []
    for url in urls:
        # split them into good and bad lists based on delay
        if not url.delay or url.delay > bad_timedelta:
            bad_urls.append(url)
        else:
            good_urls.append(url)

    context = status_info.copy()
    context.update({
        'good_urls': good_urls,
        'bad_urls': bad_urls,
        'error_logs': get_mirror_errors(),
    })
    return direct_to_template(request, 'mirrors/status.html', context)

class MirrorStatusJSONEncoder(DjangoJSONEncoder):
    '''Base JSONEncoder extended to handle datetime.timedelta and MirrorUrl
    serialization. The base class takes care of datetime.datetime types.'''
    url_attributes = ['url', 'protocol', 'last_sync', 'completion_pct',
            'delay', 'duration_avg', 'duration_stddev', 'score']

    def default(self, obj):
        if isinstance(obj, datetime.timedelta):
            # always returned as integer seconds
            return obj.days * 24 * 3600 + obj.seconds
        if hasattr(obj, '__iter__'):
            # mainly for queryset serialization
            return list(obj)
        if isinstance(obj, MirrorUrl):
            data = dict((attr, getattr(obj, attr))
                    for attr in self.url_attributes)
            # separate because it isn't on the URL directly
            data['country'] = obj.real_country
            return data
        if isinstance(obj, MirrorProtocol):
            return unicode(obj)
        return super(MirrorStatusJSONEncoder, self).default(obj)

def status_json(request):
    status_info = get_mirror_statuses()
    data = status_info.copy()
    data['version'] = 1
    to_json = simplejson.dumps(data, ensure_ascii=False,
            cls=MirrorStatusJSONEncoder)
    response = HttpResponse(to_json, mimetype='application/json')
    return response

# vim: set ts=4 sw=4 et:

VL-archweb-master/templates/mirrors/index.html
{% extends "base.html" %}
{% load package_extras %}
{% block title %}Arch Linux - Pacman Mirrorlist Generator{% endblock %}

{% block content %}
<div id="mirrorlist-gen" class="box">

    <h2>Pacman Mirrorlist Generator</h2>

    <p>This page generates the most up-to-date mirrorlist possible for Arch
    Linux. The data used here comes straight from the developers' internal
    mirror database used to track mirror availability and tiering. There are
    two main options: get a mirrorlist with every available mirror, or get a
    mirrorlist tailored to your geography.</p>

    <h3>Mirrorlist with all available mirrors</h3>

    <p>An up-to-date mirrorlist is available containing all currently active
    mirrors, optionally filtering by protocol. These URLs requires no GET or
    POST parameters so they can be fetched from the command line if desired.<p>

    <ul>
        <li><a href="all/">All mirrors</a></li>
        <li><a href="all/ftp/">All mirrors, FTP only</a></li>
        <li><a href="all/http/">All mirrors, HTTP only</a></li>
    </ul>

    <h3>Customized by country mirrorlist</h3>

    <p>The following form can generate a custom up-to-date
    <a href="https://wiki.archlinux.org/index.php/Pacman"
        title="ArchWiki: Pacman">pacman</a> mirrorlist based on geography and
    desired protocol(s).  Simply replace the contents of
    <code>/etc/pacman.d/mirrorlist</code> with your generated list.
    Additionally, the mirror status data can be incorporated into the generated
    mirror list and used to pre-order the mirrors.</p>

    <form id="list-generator" method="get">
        {{ mirrorlist_form.as_p }}
        <p><label></label> <input type="submit" value="Generate List" /></p>
    </form>
</div>
{% endblock %}

VL-archweb-master/templates/mirrors/mirror_details.html
{% extends "base.html" %}
{% load mirror_status %}

{% block title %}Arch Linux - {{ mirror.name }} - Mirror Details{% endblock %}

{% block content %}
<!-- TODO: ids and classes -->
<div id="pkgdetails" class="box">

    <h2>Mirror Details: {{ mirror.name }}</h2>

    <table id="pkginfo">
        <tr>
            <th>Name:</th>
            <td>{{ mirror.name }}</td>
        </tr>
        <tr>
            <th>Tier:</th>
            <td>{{ mirror.get_tier_display }}</td>
        </tr>
        <tr>
            <th>Country:</th>
            <td>{{ mirror.country }}</td>
        </tr>
        <tr>
            <th>Has ISOs:</th>
            <td>{{ mirror.isos|yesno|capfirst }}</td>
        </tr>
        {% if user.is_authenticated %}
        <tr>
            <th>Public:</th>
            <td>{{ mirror.public|yesno|capfirst }}</td>
        </tr>
        <tr>
            <th>Active:</th>
            <td>{{ mirror.active|yesno|capfirst }}</td>
        </tr>
        <tr>
            <th>Rsync IPs:</th>
            <td class="wrap">{{mirror.rsync_ips.all|join:', '}}</td>
        </tr>
        <tr>
            <th>Admin Email:</th>
            <td>{% if mirror.admin_email %}<a href="mailto:{{ mirror.admin_email }}">{{ mirror.admin_email }}</a>{% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Notes:</th>
            <td>{{ mirror.notes|linebreaks }}</td>
        </tr>
        <tr>
            <th>Upstream:</th>
            <td>{% if mirror.upstream %}
                <a href="{{ mirror.upstream.get_absolute_url }}"
                    title="Mirror details for {{ mirror.upstream.name }}">{{ mirror.upstream.name }}</a>
                {% else %}None{% endif %}</td>
        </tr>
        <tr>
            <th>Downstream:</th>
            {% with mirror.downstream as ds_mirrors %}
            <td>{% if ds_mirrors %}
                {% for ds in ds_mirrors %}
                <a href="{{ ds.get_absolute_url }}"
                    title="Mirror details for {{ ds.name }}">{{ ds.name }}</a>
                {% if not ds.active %}<span class="testing-dep">(inactive)</span>{% endif %}
                {% if not ds.public %}<span class="testing-dep">(private)</span>{% endif %}
                <br/>
                {% endfor %}
                {% else %}None{% endif %}</td>
            {% endwith %}
        </tr>
        {% endif %}
    </table>

    <h3>Available URLs</h3>

    <table id="available_urls" class="results">
        <thead>
            <tr>
                <th>Mirror URL</th>
                <th>IPv4</th>
                <th>IPv6</th>
                <th>Last Sync</th>
                <th>Completion %</th>
                <th>μ Delay (hh:mm)</th>
                <th>μ Duration (secs)</th>
                <th>σ Duration (secs)</th>
                <th>Mirror Score</th>
            </tr>
        </thead>
        <tbody>
            {% for m_url in urls %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td>{% if m_url.protocol.is_download %}<a href="{{ m_url.url }}">{{ m_url.url }}</a>{% else %}{{ m_url.url }}{% endif %}</td>
                <td>{{ m_url.has_ipv4|yesno|capfirst }}</td>
                <td>{{ m_url.has_ipv6|yesno|capfirst }}</td>
                <td>{{ m_url.last_sync|date:'Y-m-d H:i'|default:'unknown' }}</td>
                <td>{{ m_url.completion_pct|percentage:1 }}</td>
                <td>{{ m_url.delay|duration|default:'unknown' }}</td>
                <td>{{ m_url.duration_avg|floatformat:2 }}</td>
                <td>{{ m_url.duration_stddev|floatformat:2 }}</td>
                <td>{{ m_url.score|floatformat:1|default:'∞' }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% load cdn %}{% jquery %}
<script type="text/javascript" src="{{ STATIC_URL }}jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}archweb.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $("#available_urls:has(tbody tr)").tablesorter(
        {widgets: ['zebra'], sortList: [[0,0]],
        headers: { 6: { sorter: 'mostlydigit' }, 7: { sorter: 'mostlydigit' }, 8: { sorter: 'mostlydigit' } } });
});
</script>
{% endblock %}

VL-archweb-master/templates/mirrors/mirrors.html
{% extends "base.html" %}
{% block title %}Arch Linux - Mirror Overview{% endblock %}

{% block content %}
<div id="dev-mirrorlist" class="box">
    <h2>Mirror Overview</h2>
    <table class="results">
        <thead>
            <tr>
                <th>Server</th>
                <th>Tier</th>
                <th>Country</th>
                <th>ISOs</th>
                <th>Protocols</th>
                {% if user.is_authenticated %}
                <th>Public</th>
                <th>Active</th>
                <th>Admin Email</th>
                <th>Notes</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for mirror in mirror_list %}
            <tr class="{% cycle 'odd' 'even' %}">
                <td><a href="{{ mirror.get_absolute_url }}"
                        title="Mirror details for {{ mirror.name }}">{{ mirror.name }}</a></td>
                <td>{{mirror.get_tier_display}}</td>
                <td>{{mirror.country}}</td>
                <td>{{mirror.isos|yesno|capfirst}}</td>
                <td class="wrap">{{mirror.supported_protocols|join:", "}}</td>
                {% if user.is_authenticated %}
                <td>{{mirror.public|yesno|capfirst}}</td>
                <td>{{mirror.active|yesno|capfirst}}</td>
                <td>{{mirror.admin_email}}</td>
                <td class="wrap">{{mirror.notes|linebreaks}}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% load cdn %}{% jquery %}
<script type="text/javascript" src="{{ STATIC_URL }}jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}archweb.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $(".results").tablesorter({widgets: ['zebra'], sortList: [[1,0], [2,0]]});
});
</script>
{% endblock %}

VL-archweb-master/templates/mirrors/status_table.html
{% load mirror_status %}
<table id="{{ table_id }}" class="results">
    <thead>
        <tr>
            <th>Mirror URL</th>
            <th>Protocol</th>
            <th>Country</th>
            <th>Last Sync</th>
            <th>Completion %</th>
            <th>μ Delay (hh:mm)</th>
            <th>μ Duration (secs)</th>
            <th>σ Duration (secs)</th>
            <th>Mirror Score</th>
        </tr>
    </thead>
    <tbody>
        {% for m_url in urls %}
        <tr class="{% cycle 'odd' 'even' %}">
            <td>{{ m_url.url }}</td>
            <td>{{ m_url.protocol }}</td>
            <td>{{ m_url.real_country }}</td>
            <td>{{ m_url.last_sync|date:'Y-m-d H:i'|default:'unknown' }}</td>
            <td>{{ m_url.completion_pct|percentage:1 }}</td>
            <td>{{ m_url.delay|duration|default:'unknown' }}</td>
            <td>{{ m_url.duration_avg|floatformat:2 }}</td>
            <td>{{ m_url.duration_stddev|floatformat:2 }}</td>
            <td>{{ m_url.score|floatformat:1|default:'∞' }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>